# Generated by Django 5.0 on 2026-03-26 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['est_lue'], name='alerte_est_lue_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['niveau_urgence'], name='alerte_urgence_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['date_creation'], name='alerte_date_idx'),
        ),
    ]
