# Generated by Django 5.0 on 2026-03-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entite_concernee', models.CharField(max_length=100)),
                ('ancienne_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journal_audit',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STOCK', 'Stock'), ('COMMANDES', 'Commandes'), ('RECEPTIONS', 'Receptions'), ('ANOMALIES', 'Anomalies')], max_length=30)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'XLSX'), ('CSV', 'CSV')], default='PDF', max_length=10)),
            ],
            options={
                'db_table': 'rapport',
                'ordering': ['-date_generation'],
            },
        ),
    ]
