# Generated by Django 5.0 on 2026-03-26 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rapports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalaudit',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_audit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapport',
            name='genere_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_generes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='rapport',
            constraint=models.CheckConstraint(check=models.Q(('periode_fin__gte', models.F('periode_debut'))), name='rapport_periode_fin_gte_periode_debut'),
        ),
    ]
