# Generated by Django 5.0 on 2026-03-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0002_initial'),
        ('rapports', '0002_rapport_constraint'),
    ]

    operations = [
    ]
