# Generated by Django 6.0.3 on 2026-04-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0003_merge_0002_initial_0002_rapport_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('fonction', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('image_b64', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'signature',
            },
        ),
    ]
