# Generated by Django 6.0.3 on 2026-05-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0004_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoClinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_clinique', models.CharField(default='Ma Clinique', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('image_b64', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'logo_clinique',
            },
        ),
    ]
