# Generated by Django 5.0 on 2026-03-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonRetourFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoye'), ('TRAITE', 'Traite'), ('ANNULE', 'Annule')], default='BROUILLON', max_length=20)),
            ],
            options={
                'db_table': 'bon_retour_fournisseur',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('PARTIELLE', 'Partielle'), ('LIVREE', 'Livree'), ('ANNULEE', 'Annulee')], default='EN_ATTENTE', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'commande',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.TextField()),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fournisseur',
                'ordering': ['nom_societe'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.PositiveIntegerField()),
                ('quantite_recue', models.PositiveIntegerField(default=0)),
                ('prix_unitaire_estime', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'ligne_commande',
            },
        ),
    ]
