# Generated by Django 5.0 on 2026-03-26 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('medicaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bonretourfournisseur',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_retour_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='commandes.fournisseur'),
        ),
        migrations.AddField(
            model_name='bonretourfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_retour', to='commandes.fournisseur'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='medicaments.medicament'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut'], name='commande_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['date_creation'], name='commande_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='commande',
            constraint=models.CheckConstraint(check=models.Q(('montant_total__gte', 0)), name='commande_montant_total_gte_0'),
        ),
        migrations.AddIndex(
            model_name='bonretourfournisseur',
            index=models.Index(fields=['statut'], name='bon_retour_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='bonretourfournisseur',
            index=models.Index(fields=['date_creation'], name='bon_retour_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='lignecommande',
            constraint=models.UniqueConstraint(fields=('commande', 'medicament'), name='unique_ligne_commande_par_medicament'),
        ),
        migrations.AddConstraint(
            model_name='lignecommande',
            constraint=models.CheckConstraint(check=models.Q(('prix_unitaire_estime__gte', 0)), name='ligne_commande_prix_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='lignecommande',
            constraint=models.CheckConstraint(check=models.Q(('quantite_recue__lte', models.F('quantite_commandee'))), name='ligne_commande_recue_lte_commandee'),
        ),
    ]
