# Generated by Django 6.0.3 on 2026-05-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_merge_0002_initial_0003_commandes_hardening'),
        ('commandes', '0005_rename_prix_unitaire_estime_to_prix_achat_fournisseur'),
    ]

    operations = [
    ]
