# Generated by Django 6.0.3 on 2026-05-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_merge_20260510_1522'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lignecommande',
            name='ligne_commande_prix_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='lignecommande',
            name='ligne_commande_prix_gte_0',
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_achat_fournisseur',
            field=models.DecimalField(decimal_places=2, help_text="Prix d'achat négocié avec le fournisseur pour cette commande (FCFA). Distinct du prix de vente au patient.", max_digits=12),
        ),
    ]
