# Generated by Django 5.0 on 2026-03-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_anomalie', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Resolue')], default='OUVERTE', max_length=20)),
            ],
            options={
                'db_table': 'anomalie',
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifie'), ('EN_COURS', 'En cours'), ('CLOTURE', 'Cloture')], default='PLANIFIE', max_length=20)),
            ],
            options={
                'db_table': 'inventaire',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='LigneReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recue', models.PositiveIntegerField()),
                ('numero_lot', models.CharField(max_length=100)),
                ('date_peremption', models.DateField()),
                ('prix_achat_reel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('has_anomalie', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ligne_reception',
            },
        ),
        migrations.CreateModel(
            name='LotStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=100)),
                ('date_peremption', models.DateField()),
                ('quantite_disponible', models.PositiveIntegerField(default=0)),
                ('quantite_quarantaine', models.PositiveIntegerField(default=0)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_reception', models.DateField()),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('QUARANTAINE', 'Quarantaine'), ('EPUISE', 'Epuise'), ('EXPIRE', 'Expire')], default='DISPONIBLE', max_length=20)),
            ],
            options={
                'db_table': 'lot_stock',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entree'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement'), ('TRANSFERT', 'Transfert')], max_length=20)),
                ('type_motif', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField()),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('numero_ordre', models.CharField(blank=True, max_length=100)),
                ('patient_nom', models.CharField(blank=True, max_length=150)),
                ('prescripteur', models.CharField(blank=True, max_length=150)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'mouvement_stock',
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.DateTimeField()),
                ('numero_bon_livraison', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIELLE', 'Partielle'), ('COMPLETE', 'Complete')], default='EN_ATTENTE', max_length=20)),
            ],
            options={
                'db_table': 'reception',
                'ordering': ['-date_reception'],
            },
        ),
    ]
