# Generated by Django 5.0 on 2026-03-26 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_initial'),
        ('medicaments', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='signale_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies_signalees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='initie_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires_inities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignereception',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_reception', to='medicaments.medicament'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='ligne_reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='stock.lignereception'),
        ),
        migrations.AddField(
            model_name='lotstock',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='medicaments.medicament'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stock.lotstock'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reception',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='reception',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions_enregistrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignereception',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.reception'),
        ),
        migrations.AddConstraint(
            model_name='inventaire',
            constraint=models.CheckConstraint(check=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='inventaire_date_fin_gte_date_debut'),
        ),
        migrations.AddIndex(
            model_name='anomalie',
            index=models.Index(fields=['statut'], name='anomalie_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalie',
            index=models.Index(fields=['date_signalement'], name='anomalie_date_idx'),
        ),
        migrations.AddIndex(
            model_name='lotstock',
            index=models.Index(fields=['date_peremption'], name='lot_stock_peremption_idx'),
        ),
        migrations.AddIndex(
            model_name='lotstock',
            index=models.Index(fields=['statut'], name='lot_stock_statut_idx'),
        ),
        migrations.AddConstraint(
            model_name='lotstock',
            constraint=models.UniqueConstraint(fields=('medicament', 'numero_lot'), name='unique_lot_par_medicament'),
        ),
        migrations.AddConstraint(
            model_name='lotstock',
            constraint=models.CheckConstraint(check=models.Q(('prix_achat__gte', 0)), name='lot_stock_prix_achat_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='lotstock',
            constraint=models.CheckConstraint(check=models.Q(('date_peremption__gte', models.F('date_reception'))), name='lot_stock_peremption_gte_reception'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement'], name='mvt_stock_type_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['date_operation'], name='mvt_stock_date_idx'),
        ),
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['statut'], name='reception_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['date_reception'], name='reception_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='lignereception',
            constraint=models.CheckConstraint(check=models.Q(('prix_achat_reel__gte', 0)), name='ligne_reception_prix_gte_0'),
        ),
    ]
