# Generated by Django 5.0 on 2026-03-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_initial'),
        ('stock', '0003_stock_hardening'),
    ]

    operations = [
    ]
