# Generated by Django 6.0.3 on 2026-04-11 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0002_medicament_hardening'),
        ('stock', '0004_merge_0002_initial_0003_stock_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.PositiveIntegerField(default=0)),
                ('quantite_physique', models.PositiveIntegerField(default=0)),
                ('ecart', models.IntegerField(default=0)),
                ('justification', models.TextField(blank=True, default='')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.inventaire')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_inventaire', to='medicaments.medicament')),
            ],
            options={
                'db_table': 'ligne_inventaire',
                'unique_together': {('inventaire', 'medicament')},
            },
        ),
    ]
