# Generated by Django 5.0 on 2026-03-26 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'categorie',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(max_length=150)),
                ('dci', models.CharField(max_length=150)),
                ('forme_galenique', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('unite_stock', models.CharField(max_length=50)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('seuil_alerte', models.PositiveIntegerField(default=0)),
                ('conditions_stockage', models.TextField(blank=True)),
                ('indications_therapeutiques', models.TextField(blank=True)),
                ('code_barres', models.CharField(max_length=100, unique=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicaments', to='medicaments.categorie')),
            ],
            options={
                'db_table': 'medicament',
                'ordering': ['nom_commercial'],
                'indexes': [models.Index(fields=['nom_commercial'], name='medicament_nom_idx'), models.Index(fields=['est_actif'], name='medicament_actif_idx'), models.Index(fields=['seuil_alerte'], name='medicament_seuil_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='medicament',
            constraint=models.CheckConstraint(check=models.Q(('prix_unitaire__gte', 0)), name='medicament_prix_unitaire_gte_0'),
        ),
    ]
