# Generated by Django 6.0.3 on 2026-05-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0003_rename_prix_unitaire_to_prix_vente'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='medicament',
            name='medicament_seuil_idx',
        ),
        migrations.RenameIndex(
            model_name='medicament',
            new_name='med_nom_idx',
            old_name='medicament_nom_idx',
        ),
        migrations.RenameIndex(
            model_name='medicament',
            new_name='med_actif_idx',
            old_name='medicament_actif_idx',
        ),
        migrations.AlterField(
            model_name='medicament',
            name='code_barres',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='conditions_stockage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='dci',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='forme_galenique',
            field=models.CharField(choices=[('Comprimé', 'Comprimé'), ('Gélule', 'Gélule'), ('Sirop', 'Sirop'), ('Injectable', 'Injectable'), ('Pommade', 'Pommade'), ('Capsule', 'Capsule'), ('Suppositoire', 'Suppositoire'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='unite_stock',
            field=models.CharField(default='unité', max_length=50),
        ),
    ]
